name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-via-rsync:
    uses: max13/zero-downtime/.github/workflows/deploy-via-rsync-ssh.yml@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: "${{ secrets.SSH_PORT }}"
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_BASE_PATH: ${{ secrets.SSH_BASE_PATH }}
#      SSH_SYMLINK_PATH: 'staging'
    with:
#      SCRIPT_AFTER_CHECKOUT:
#      SCRIPT_AFTER_DST_SETUP:
      SCRIPT_BEFORE_UPLOAD: |
        composer config --global github-oauth.github.com $ACCESS_TOKEN
        composer install -n -o --no-dev --no-scripts
        npm install
        npm run production
      SCRIPT_ON_DST_BEFORE_DEPLOY: |
        SSHPASS="$SSH_PASSWORD" sshpass -e ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_PORT "$SSH_USERNAME"@"$SSH_HOST" "rm -rf \"$SSH_RELEASE_PATH\"/.ovhconfig && ln -sfnr \"$SSH_BASE_PATH\"/data/.ovhconfig \"$SSH_RELEASE_PATH\"/"
        SSHPASS="$SSH_PASSWORD" sshpass -e ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_PORT "$SSH_USERNAME"@"$SSH_HOST" "rm -rf \"$SSH_RELEASE_PATH\"/.env && ln -sfnr \"$SSH_BASE_PATH\"/data/.env \"$SSH_RELEASE_PATH\"/"
        SSHPASS="$SSH_PASSWORD" sshpass -e ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_PORT "$SSH_USERNAME"@"$SSH_HOST" "rm -rf \"$SSH_RELEASE_PATH\"/database/database.sqlite && ln -sfnr \"$SSH_BASE_PATH\"/data/database/database.sqlite \"$SSH_RELEASE_PATH\"/database/"
        SSHPASS="$SSH_PASSWORD" sshpass -e ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_PORT "$SSH_USERNAME"@"$SSH_HOST" "rm -rf \"$SSH_RELEASE_PATH\"/storage/app && ln -sfnr \"$SSH_BASE_PATH\"/data/storage/app \"$SSH_RELEASE_PATH\"/storage/"
        SSHPASS="$SSH_PASSWORD" sshpass -e ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_PORT "$SSH_USERNAME"@"$SSH_HOST" "php \"$SSH_RELEASE_PATH\"/artisan storage:link"
#      SCRIPT_ON_DST_AFTER_DEPLOY:
